from . import cowork_project_priority
from . import cowork_project_difficulty
from . import cowork_project_apply
from . import cowork_project_estimate
from . import cowork_scheme_preliminary
from . import cowork_project_charger
from . import cowork_attachment_line
from . import cowork_cost_labor
from . import cowork_cost_labor_quote
from . import cowork_cost_material
from . import cowork_material_class
from . import cowork_material_category
from . import cowork_cost_material_detail_line
from . import cowork_cost_material_detail_line_quote
from . import cowork_spare_part_line
from . import product_brand
from . import cowork_quote_order
from . import cowork_bom
from . import cowork_purchase_order
from . import cowork_purchase_order_line
from . import stock
from . import cowork_message
from . import res_partner
from . import supplier_approval
from . import cowork_contract
from . import mail_activity